### ISSUE TITLE
Learn about the usage of br tag

### ISSUE THREAD

**Issue by jjw18th** [jjw18th/TO-DO#2]
Went through the mdn document to learn the usage of br tag.

**Comment by jjw18th** [comment]
The `<br>` html element produces a line break in text. It is useful for writing a poem or an address, where the division of lines is significant.

The only purpose of `<br>` is to create a line break in a block of text. We should not use <br> to create margins between paragraphs. We could use CSS margin property to control their spacing.

**Comment by n0x3u5** [comment]
@jjw18th Could you please format the previous comment correctly so its more understandable?

**Comment by jjw18th** [comment]
Is it fine now?

**Comment by n0x3u5** [comment]
Yes. its good now. Closing.
