### ISSUE TITLE
Learn about the usage of various types of buttons

### ISSUE THREAD

**Issue by jjw18th** [jjw18th/TO-DO#3]
Learn about input button of type submit, buttons type submit, normal buttons.

**Comment by jjw18th** [comment]
The various types of buttons:

1. The submit button submits the form data to the server and is the default behaviour if the attribute is not specified.
2. The reset button resets all the controls to their initial values just like <input type="reset">
3. The button of type button has no default behaviour. It can be used to listen to the element's events, which are triggered when the events occur.

**Comment by n0x3u5** [comment]
@jjw18th 
1. What about a `button` without any type specified in its attribute list?
2. Will these button behave the same way if they are not nested within a `form`?

**Comment by jjw18th** [comment]
For a button without any type specified in its attribute list, it will behave like a submit button in case it is associated with a form element. However if we have button element without form , it has no default behaviour and can be manipulated through Javascript.

**Comment by n0x3u5** [comment]
Alright! That's good. Closing.
