### ISSUE TITLE
Use semantic HTML tags to structure the overall page

### ISSUE THREAD

**Issue by n0x3u5** [jjw18th/TO-DO#8]
Use semantic HTML tags to partition the header & the mode switcher, the main content of the app (task adder & tasklist) and the Delete all/Clear all buttons into individual sections.

**Comment by jjw18th** [comment]
Added the header and the mode switcher in the section tag, the main content of the app (tasklist) is added in the main tag, all the buttons are wrapped in the section tag. Did not use any tag to partition the task adder.
